# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/i62macaf/Desktop/Luque_Cordoba_y_Maestre_Carmona

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/i62macaf/Desktop/Luque_Cordoba_y_Maestre_Carmona

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/i62macaf/Desktop/Luque_Cordoba_y_Maestre_Carmona/CMakeFiles /home/i62macaf/Desktop/Luque_Cordoba_y_Maestre_Carmona/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/i62macaf/Desktop/Luque_Cordoba_y_Maestre_Carmona/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ServidorB

# Build rule for target.
ServidorB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ServidorB
.PHONY : ServidorB

# fast build rule for target.
ServidorB/fast:
	$(MAKE) -f CMakeFiles/ServidorB.dir/build.make CMakeFiles/ServidorB.dir/build
.PHONY : ServidorB/fast

#=============================================================================
# Target rules for targets named ClienteB

# Build rule for target.
ClienteB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClienteB
.PHONY : ClienteB

# fast build rule for target.
ClienteB/fast:
	$(MAKE) -f CMakeFiles/ClienteB.dir/build.make CMakeFiles/ClienteB.dir/build
.PHONY : ClienteB/fast

ClienteBuscaminas.o: ClienteBuscaminas.cpp.o

.PHONY : ClienteBuscaminas.o

# target to build an object file
ClienteBuscaminas.cpp.o:
	$(MAKE) -f CMakeFiles/ClienteB.dir/build.make CMakeFiles/ClienteB.dir/ClienteBuscaminas.cpp.o
.PHONY : ClienteBuscaminas.cpp.o

ClienteBuscaminas.i: ClienteBuscaminas.cpp.i

.PHONY : ClienteBuscaminas.i

# target to preprocess a source file
ClienteBuscaminas.cpp.i:
	$(MAKE) -f CMakeFiles/ClienteB.dir/build.make CMakeFiles/ClienteB.dir/ClienteBuscaminas.cpp.i
.PHONY : ClienteBuscaminas.cpp.i

ClienteBuscaminas.s: ClienteBuscaminas.cpp.s

.PHONY : ClienteBuscaminas.s

# target to generate assembly for a file
ClienteBuscaminas.cpp.s:
	$(MAKE) -f CMakeFiles/ClienteB.dir/build.make CMakeFiles/ClienteB.dir/ClienteBuscaminas.cpp.s
.PHONY : ClienteBuscaminas.cpp.s

ServidorBuscaminas.o: ServidorBuscaminas.cpp.o

.PHONY : ServidorBuscaminas.o

# target to build an object file
ServidorBuscaminas.cpp.o:
	$(MAKE) -f CMakeFiles/ServidorB.dir/build.make CMakeFiles/ServidorB.dir/ServidorBuscaminas.cpp.o
.PHONY : ServidorBuscaminas.cpp.o

ServidorBuscaminas.i: ServidorBuscaminas.cpp.i

.PHONY : ServidorBuscaminas.i

# target to preprocess a source file
ServidorBuscaminas.cpp.i:
	$(MAKE) -f CMakeFiles/ServidorB.dir/build.make CMakeFiles/ServidorB.dir/ServidorBuscaminas.cpp.i
.PHONY : ServidorBuscaminas.cpp.i

ServidorBuscaminas.s: ServidorBuscaminas.cpp.s

.PHONY : ServidorBuscaminas.s

# target to generate assembly for a file
ServidorBuscaminas.cpp.s:
	$(MAKE) -f CMakeFiles/ServidorB.dir/build.make CMakeFiles/ServidorB.dir/ServidorBuscaminas.cpp.s
.PHONY : ServidorBuscaminas.cpp.s

buscaminas.o: buscaminas.cpp.o

.PHONY : buscaminas.o

# target to build an object file
buscaminas.cpp.o:
	$(MAKE) -f CMakeFiles/ServidorB.dir/build.make CMakeFiles/ServidorB.dir/buscaminas.cpp.o
	$(MAKE) -f CMakeFiles/ClienteB.dir/build.make CMakeFiles/ClienteB.dir/buscaminas.cpp.o
.PHONY : buscaminas.cpp.o

buscaminas.i: buscaminas.cpp.i

.PHONY : buscaminas.i

# target to preprocess a source file
buscaminas.cpp.i:
	$(MAKE) -f CMakeFiles/ServidorB.dir/build.make CMakeFiles/ServidorB.dir/buscaminas.cpp.i
	$(MAKE) -f CMakeFiles/ClienteB.dir/build.make CMakeFiles/ClienteB.dir/buscaminas.cpp.i
.PHONY : buscaminas.cpp.i

buscaminas.s: buscaminas.cpp.s

.PHONY : buscaminas.s

# target to generate assembly for a file
buscaminas.cpp.s:
	$(MAKE) -f CMakeFiles/ServidorB.dir/build.make CMakeFiles/ServidorB.dir/buscaminas.cpp.s
	$(MAKE) -f CMakeFiles/ClienteB.dir/build.make CMakeFiles/ClienteB.dir/buscaminas.cpp.s
.PHONY : buscaminas.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ServidorB"
	@echo "... ClienteB"
	@echo "... ClienteBuscaminas.o"
	@echo "... ClienteBuscaminas.i"
	@echo "... ClienteBuscaminas.s"
	@echo "... ServidorBuscaminas.o"
	@echo "... ServidorBuscaminas.i"
	@echo "... ServidorBuscaminas.s"
	@echo "... buscaminas.o"
	@echo "... buscaminas.i"
	@echo "... buscaminas.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

